#!/bin/bash

usage()
{
  echo 'Usage: ydl-cf -jar <path_to_caffe-with-dependency_jar>'
  echo '               -conf <your_solver_protoxt>'
  echo '               -model <model_output_hdfs_path>'
  echo '               -num <container_num>'
  exit
}

conf=""
feature=""
label=""
model=""
output=""
num=0
jar=""

while true
do
    echo "$1"
    case "$1" in
         -conf)
            conf="$2"
            echo "conf: $conf"
            shift
         ;;
         -model)
            model="$2"
            echo "model: $model"
            shift
         ;;
         -num)
            num="$2"
            echo "num: $num"
            shift
         ;;
         -jar)
            jar="$2"
            echo "jar path: $jar"
            shift
         ;;
         "")
            break
         ;;
         *)
            usage
         ;;
    esac
shift
done

CLIENT_MAIN_CLASS="org.hdl.caffe.yarn.app.Client"

yarn jar $jar $CLIENT_MAIN_CLASS \
         --jar $jar \
         --conf $conf \
         --model $model \
         --num $num \
         --label label \
         --container_memory 2048 \
         --feature accuracy,loss \
         --output hdfs:///mnist_features_result
